In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]

In [3]:
a = np.array(lst)

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b = [[1,2,3], [4,5,6]]

In [6]:
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# Create a 1-dimensional NumPy array with 12 elements
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print("Original array:")
print(arr)

# Reshape the array into a 3x4 matrix (3 rows, 4 columns)
reshaped_arr = np.reshape(arr, (3, 4))
print("\nReshaped array (3x4):")
print(reshaped_arr)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [54]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# aggregation function

a.max()

5

In [13]:
a.min()

1

In [14]:
a

array([1, 2, 3, 4, 5])

In [63]:
a.argmax() # index value

4

In [64]:
a.argmin()

0

In [15]:
a.dtype

dtype('int64')

In [17]:
a1 = a[:1]

In [18]:
a1

array([1])

In [19]:
a1[0] = 10

In [20]:
a # no changes

array([10,  2,  3,  4,  5])

In [21]:
b = a.copy()

In [22]:
b

array([10,  2,  3,  4,  5])

In [24]:
b[0] = 11

In [25]:
b

array([11,  2,  3,  4,  5])

In [26]:
a

array([10,  2,  3,  4,  5])

In [27]:
b

array([11,  2,  3,  4,  5])

In [28]:
# broadcasting

x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
y = np.array([1,2,3])

In [71]:
z = x + y

In [72]:
z

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [30]:
# conditional array

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
condition = arr > 5

In [32]:
print(condition)

[False False False False False False  True  True  True  True]


In [33]:
filtered_arr = arr[condition]

In [34]:
print(filtered_arr)

[6 7 8 9]


In [35]:
# operation
arr + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [37]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
arr / 1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
# mathematical function

# Create a NumPy array with values in radians
radian_values = np.array([0, np.pi / 6, np.pi / 4, np.pi / 3, np.pi / 2])

print("Input array in radians:")
print(radian_values)

# Compute the sine of each element in the array
sine_values = np.sin(radian_values)

print("\nSine values of the input array:")
print(sine_values)

Input array in radians:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine values of the input array:
[0.         0.5        0.70710678 0.8660254  1.        ]


In [110]:
# aggregation function

# Create a 2-dimensional NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original array:")
print(arr)

# Compute the product of all elements in the array
total_product = np.prod(arr)
print("\nTotal product of all elements:", total_product)

# Compute the product of elements along the rows (axis=1)
row_products = np.prod(arr, axis=1)
print("\nProduct of elements along the rows:", row_products)

# Compute the product of elements along the columns (axis=0)
column_products = np.prod(arr, axis=0)
print("\nProduct of elements along the columns:", column_products)

Original array:
[[1 2 3]
 [4 5 6]]

Total product of all elements: 720

Product of elements along the rows: [  6 120]

Product of elements along the columns: [ 4 10 18]


In [119]:
# Create a 2-dimensional NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original array:")
print(arr)

# Compute the cumulative sum of all elements in the array
total_cumsum = np.cumsum(arr)
print("\nTotal cumulative sum of all elements:")
print(total_cumsum)

# Compute the cumulative sum of elements along the rows (axis=1)
row_cumsum = np.cumsum(arr, axis=1)
print("\nCumulative sum of elements along the rows:")
print(row_cumsum)

# Compute the cumulative sum of elements along the columns (axis=0)
column_cumsum = np.cumsum(arr, axis=0)
print("\nCumulative sum of elements along the columns:")
print(column_cumsum)

Original array:
[[1 2 3]
 [4 5 6]]

Total cumulative sum of all elements:
[ 1  3  6 10 15 21]

Cumulative sum of elements along the rows:
[[ 1  3  6]
 [ 4  9 15]]

Cumulative sum of elements along the columns:
[[1 2 3]
 [5 7 9]]
